### ISSUE TITLE
Revise Output File Views

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicatorAfter#116]
@Tilmon I created this ticket as a placeholder to discuss one more time the view of the output files. This follows those discussions [here](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/113).

Re simplification & wide vs long format

I think we should think about simplifying it. There are a lot of double information and maybe would be great to have only one file similar to this ING here: https://docs.google.com/spreadsheets/d/1rRUBpeXfj1w-paAX0Cono7RslZX_kzoujYE1E7XdnaM/edit#gid=1842238901 @Tilmon what do you think?

@AnneSchoenauer I think the downside of the link you shared is that this would require to make separate columns for each benchmark (i.e. scenarios for sector_profile and the other benchmarks for emission_profile). Right now, we have it all in the long format instead of wide format. This then already relates to your comment here

For the company view - I noticed that it is super important when doing econemtric that we need not a long but a wide view. Could we create both? @Tilmon what do you think? I also think that for some plots we need wide view so maybe good to have the view that is best compatible for further analysis? @Tilmon what do you think?

@AnneSchoenauer Providing both to banks might be a bit of an overkill BUT we could provide code to modify datasets to wide format AND join all company-level results together and all product-level results? I assume that's possible and would also solve the "simplifying" question you raised above. 

Next step is to decide on a view. Also we need to understand on how to view the transition risk score calculated in ticket #650.

**Comment by Tilmon** [comment]
@AnneSchoenauer this is done now since we have a new output view for Bundesbank, right? If so, please close :) Thanks!
