### ISSUE TITLE
Adding GEO column to emission_profile_upstream and sector_profile_upstream at product level

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicatorAfter#119]
Would be great to add the GEO column per input_product. Thanks!

**Comment by kalashsinghal** [comment]
@AnneSchoenauer What's the name of GEO column should be? Does `ei_input_geography` sound good?

**Comment by AnneSchoenauer** [comment]
@kalashsinghal how is the geo column called on product level? If it is `ei_geography.`  I think the `ei_input_geography` would work fine!

**Comment by kalashsinghal** [comment]
@AnneSchoenauer The geo column is not present in the product level result. Hence, I will add it through the `ei_input_data` file, which is used to add other columns. I forgot to mention that the column name is `input_geography` in this file. Is it still ok to keep the column name as `ei_input_geogrphy`?

**Comment by AnneSchoenauer** [comment]
@kalashsinghal it would also be great to add the geo column in the product dataset. So it would be `ei_geography` and `ei_input_geograhy`. Thanks :)

**Comment by kalashsinghal** [comment]
@AnneSchoenauer Just to be 100% clear, We can add `ei_geography` column in `emission_profile` and `sector_profile` at product level, and we can add both `ei_geography` and `ei_input_geography` in `emission_profile_upstream` and `sector_profile_upstream` at product level (as they have both main products and input products). Should I add geography columns in all the four indicators in the way I described?

**Comment by AnneSchoenauer** [comment]
@kalashsinghal yes exactly :) Thanks a lot!
