### ISSUE TITLE
Company-level output not occurring for some companies when run will all unique companies

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicatorAfter#16]
Dear @maurolepore 

Please run the tiltIndicator and tiltIndicatorAfter code for PCTR to see that the company level output for PCTR is not occurring for all the unique company ids. 

Please use this .Rmd file to run the complete flow for PCTR: https://github.com/2DegreesInvesting/tiltIndicatorAfter/blob/main/inst/extdata/tiltIndicatorAfter_runner_pctr.Rmd

And use the input data from this folder for the script: https://drive.google.com/drive/folders/1AbSGCGFVcRM3zLfPg5FdwScTRRaCbIws

I am asking you to identify the issue because I don't understand the fact that the output for company ids - `3b-berlin-premium-hotelservice-gmbh_00000004908165-001`, `1-4-de-vin_fra356206-00101`, and `12-lowen-gmbh_00000005117196-001` are occurring in the company level output if the code run is performed separately for these ids, however final company level output for these companies are not occurring if the code run is performed with all unique company ids. 

FYI: In total there are 287978 unique companies in the final output of product level result. The unique ids in company level results are not the same for all the indicators (which is undesirable).

Please let me know if you need a separate meting to discuss this issue because of lack of understand on this issue! Thanks!

**Comment by maurolepore** [comment]
I was able to reproduce your problem with the the full companies dataset, and also with a much smaller one:

* With 4 rows I get the problem: Some companies appear at product but not company level.
* With 3 rows I don't get the problem: All companies appear at both levels.

While I haven't found the exact problem to explain why the problem appears only sometimes, I did find one specific problem that seems to be implicated. When A company has `NA` in `*uuid` the it has a product level result with `NA` in important columns (which seems fine) but it dissapears from the company level result (which is unexpected).  I'll tackle this problem first. Hopefully that fixed the bug you see.

https://gist.github.com/maurolepore/c642f6f326bf131ac723ba816c35ff0a

Handling unmatched results has been the biggest source of bugs -- as the requirements and necessary logic is complex.
