### ISSUE TITLE
Add `min_headcount` and `max_headcount`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#177]
* Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153

Get `min_headcount` and `max_headcount` from tiltData then add it to the output of tiltIndicatorAfter by `companies_id`.

[headcount.csv.gz](https://github.com/2DegreesInvesting/tiltIndicatorAfter/files/14539271/headcount.csv.gz)

<details/>
<summary/>
reprex
</summary>

``` r
# # Source: https://github.com/2DegreesInvesting/tiltData/releases/tag/v1.1.0
library(readr, warn.conflicts = FALSE)
withr::local_options(readr.show_col_types = FALSE)
# 
# "~/Downloads/tiltData-v1.1.0/companies.csv" |> 
# read_csv(col_select = c(companies_id, min_headcount, max_headcount)) |> 
#   write_csv("~/Downloads/headcount.csv.gz")

read_csv("~/Downloads/headcount.csv.gz")
#> # A tibble: 287,978 × 3
#>    companies_id                                      min_headcount max_headcount
#>    <chr>                                                     <dbl>         <dbl>
#>  1 neubauer-gesmbh-co-kg_00000005392900-001                     11            50
#>  2 plansee-se_00000005184493-001                               501           Inf
#>  3 pohl-metall-gmbh_00000005224526-001                          11            50
#>  4 gilo-metallbau-gilo-sonderpulverbeschichtungs-gm…            11            50
#>  5 enviral-oberflachenveredelung-gmbh_aut054195-001…             1            10
#>  6 protec-trading-gmbh_00000005190160-656856001                  1            10
#>  7 otto-weisleitner-gesmbh_00000005184790-001                   11            50
#>  8 gemos-meisterwerkstatt-fur-glas-und-metallgestal…             1            10
#>  9 hanjes-co-stahlbau-gesmbh_00000005346484-001                101           200
#> 10 joachim-sachverstandigenburo-f-gebaudehullen-gla…            NA            NA
#> # ℹ 287,968 more rows
```

</details>

> Add the columns min_headcount and max_headcount. These variables should be included in the tiltData that you webscraped from europages. 
--Anne

----

QUESTIONS

- [x] ml01. @AnneSchoenauer, how would you calculate `employee_size`? Maybe like this?:

```r
employee_size = max_headcount - min_headcount
```

- [x] ml02. @AnneSchoenauer I don't understand what you're asking for here:

> Please note that I think we still use the information in 2022 - so it would be great if the employee data matches with this point in time of when we webscraped the information.

For any one company all the information we have comes from the same web page, so each data point we have for each company was scraped at the same time (i.e. by downloading its web page then pulling each of the datapoints we care about). 

For example note the many "data points" in the web page of [this company](https://www.europages.co.uk/FACANAMO/00000005437617-001.html)

![image](https://github.com/2DegreesInvesting/tiltIndicatorAfter/assets/5856545/6e3095bb-3369-418a-9099-4fe1db93ae0e)

I suspect you refer to some rare case where we may have scraped a specific data point (maybe keywords?) more than once and somehow used it to "update" otherwise existing data? Likely you have this more fresh in your mind than I do, so please explain.

- [x] ml03. @AnneSchoenauer, what did you change? What was it before and what is it now?

> I changed it in this data sheet here: https://docs.google.com/spreadsheets/d/1Gsz2N2-gqrttAooYuNgWrKfjLyA73Uj4w0xm_wN7fp4/edit#gid=1500707263.
-- Anne https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-1971601869

ANSWERS

* ml01. Don't calculate `employee_size`. Use `min_headcount` and `max_headcount`.
* ml02. Don't worry. The conversation is still unclear but no action seems necessary.
* ml03. Don't worry. Anne refers to changes in the googlesheet she is using to show the output she wants.

**Comment by AnneSchoenauer** [comment]
Hi Mauro,
With regard to M1 - two columns with `min_headcoun`t and `max_headcount` are fine. I already added the two columns in the dataset. I will use it later for categorisation purposes and if we cannot say if the range is 1-10 if the company has 4, 7 or 10 employees the range is fine! 

M2 - perfect! I had in mind that we also webscraped the data again in 2023 but I guess I confused it with the newly webscraped data for Italy and UK. All fine then! Thanks for checking in! 

M3 - before I only had a column which was called employee_size, now I added min_headcount as one column and max_headcount as column. I also deleted the sector_categories with low, medium and high at product level and company level as we don’t need it for the Bundesbank. The data in the Google sheet should be up to date. 

Please note that I think Kalash already created all functions for all parts of the dataset, e.g (average_)transition_risk_score. I think the only column which is not in the tiltIndicator package is CO2_average on the company data sheet. Now it is late but I will try to make a reprex tomorrow evening. I am at the Bundesbank all day tomorrow but thereafter I will write a reprex. However, I think you can already start with the rest.

**Comment by maurolepore** [comment]
> Please note that I think Kalash already created all functions for all parts of the dataset, e.g (average_)transition_risk_score. I think the only column which is not in the tiltIndicator package is CO2_average on the company data sheet. Now it is late but I will try to make a reprex tomorrow evening. I am at the Bundesbank all day tomorrow but thereafter I will write a reprex. However, I think you can already start with the rest.

@AnneSchoenauer this thread relates to `employee_size` or `min_headcount` and `max_headcount`. Maybe this comment is relevant here?: https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/182

**Comment by AnneSchoenauer** [comment]
With regard to your last comment - this is a comment that belongs in ticket#178 which can be found here: https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/178#issuecomment-1980239898

**Comment by kalashsinghal** [comment]
I extracted the [headcount.csv](https://github.com/2DegreesInvesting/tiltIndicatorAfter/files/14742462/headcount.csv) file from tiltData and it is used to create Bundesbank data [here](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-2004469926).
