### ISSUE TITLE
Add CO2 footprint

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#178]
* Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153

Task list

* https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/183
* https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/185

QUESTIONS

- [x] ml01. At product level

> On hte product level it is the "standard" Co2 variable data point that you guys know. 

@AnneSchoenauer do you mean these two columns?:

* `emissions_profile_products_ecoinvent$co2_footprint`
* `emissions_profile_upstream_products_ecoinvent$input_co2_footprint`

([You may search for "co2_footprint" here](https://2degreesinvesting.github.io/tiltToyData/index.html#example).)

Note these columns are currently excluded. To include them we'll need some changes in the code. Maybe we can allow to include them with a new option `tiltIndicatorAfter.keep_licensed_co2_footprint`, similar to `tiltIndicatorAfter.co2_keep_licensed_min_max` ([helpfile](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/tiltIndicatorAfter_options)).

- [x] ml02. At company level

> On the company level (sheet 2 in the Bundesbank data file) is the average Co2 variable of all products. I think Kalash wrote a function for the profile ranking and sector targets which is called profile_ranking_avg and reduction_targets_avg - what we would need in the same logic is a co2_avg on the company level.

OK, I'll dig into the code to see if Kalash did something more complex than I imagine. But from your comment  I understand you simply want to calculate the mean of `co2_footprint` and `input_co2_footprint` grouped by `companies_id`.

@AnneSchoenauer, can you please see if this reprex captures the essence of what you want?

<details/>
<summary/>
reprex
</summary>

``` r
library(dplyr, warn.conflicts = FALSE)

# Missing values should be excluded from the summary, so in this example
# `co2_avg` should be the same for company "a" and "b"

result_at_product_level <- tribble(
  ~companies_id, ~activity_uuid_product_uuid, ~co2_footprint,
            "a",                         "x",              1,
            "a",                         "y",              2,
            "a",                         "z",              3,

            "b",                         "a",              1,
            "b",                         "b",              2,
            "b",                         "c",              3,
            "b",                         "d",             NA
)

# Good
result_at_product_level |> 
  summarize(co2_avg = mean(co2_footprint, na.rm = TRUE) , .by = "companies_id")
#> # A tibble: 2 × 2
#>   companies_id co2_avg
#>   <chr>          <dbl>
#> 1 a                  2
#> 2 b                  2

# Bad
result_at_product_level |> 
  summarize(co2_avg = mean(co2_footprint) , .by = "companies_id")
#> # A tibble: 2 × 2
#>   companies_id co2_avg
#>   <chr>          <dbl>
#> 1 a                  2
#> 2 b                 NA
```

</details>

ANSWERS

* ml01. Only `emissions_profile_products_ecoinvent$co2_footprint` (exclude `*_upstream()`).
* ml02. Yes, the reprex reflects the essence of what we want.

**Comment by AnneSchoenauer** [comment]
M2 - Yes this is exactly what we imagined here. Please note that if the company produces a product that is not matched with Ecoinvent so company a produces product d which doesn’t have a CO2 footprint that the average would still be the same as you showed in the reprex - so i.e. NAs would not be included in the calculations. 

To be even more concrete: we would still calculate (1+2+3)/3 and not (1+2+3)/4.

**Comment by AnneSchoenauer** [comment]
Also this comment here:  

> Please note that I think Kalash already created all functions for all parts of the dataset, e.g (average_)transition_risk_score. I think the only column which is not in the tiltIndicator package is CO2_average on the company data sheet. Now it is late but I will try to make a reprex tomorrow evening. I am at the Bundesbank all day tomorrow but thereafter I will write a reprex. However, I think you can already start with the rest.

Belonged to this ticket here and to question M2. I will indicate it in the other ticket.

**Comment by AnneSchoenauer** [comment]
M1- at product level: please note that for the Bundesbank data we don’t need any input data so there is no upstream profiles involved. Therefore, we only need this column here: `emissions_profile_products_ecoinvent$co2_footprint` correct.

**Comment by maurolepore** [comment]
This issue already served its purpose and I'll close it now in favor of the two more granular issues described in the task list at the top.
