### ISSUE TITLE
Add `lower_bound` and `higher_bound`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#179]
* Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153

> Please note that Mauro still works on the lower_bound and higher_bound plus the NAs. However, I think you could already start however with creating the dataset and prepare them and then add the columns and row thereafter.
--Anne https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issue-2129684586

QUESTION

@AnneSchoenauer do you mean the new columns `co2e_lower` and `co2e_upper` we recently added to tiltIndicatorAfter?

From the [changelog](https://2degreesinvesting.github.io/tiltIndicatorAfter/news/index.html):

> New columns co2e_lower and co2e_upper in the output of [profile_emissions()](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html) and [profile_emissions_upstream()](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html) – both at product and company levels. This columns include some noise that protects the privacy of the licensed CO2 values ([@kalashsinghal](https://github.com/kalashsinghal) [#155](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/155)).

ANSWERS

ml01. Yes.

**Comment by AnneSchoenauer** [comment]
Yes they are the same and happy if we call them CO2_lower and CO2_upper.

**Comment by maurolepore** [comment]
Note we don't call them `CO2_lower` and `CO2_upper` but `co2e_lower` and `co2e_upper`. 

If you want a different name please open a separate issue and discuss with Kalash. But I guess the name is less important than the content so I'll assume it's all fine for now.

**Comment by maurolepore** [comment]
Closing this issue since the required columns already exist in the output of tiltIndicatorAfter.
