### ISSUE TITLE
Add `transition_risk_score_avg` and `benchmark_transition_risk_score_avg`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#182]
* Relates to #153 

--

* `transition_risk_score_avg` already exists in the output of [`score_transition_risk()` (see the example)](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/score_transition_risk.html#ref-examples). 
* `benchmark_transition_risk_score_avg` also exists but with the name `benchmark_tr_score`.

--

> there is a new column average_co2, for which which you might need more insight from @AnneSchoenauer
--https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-1966663425

> There is one new feature in the data namely having the averages of the products when aggregating it to the company level. It is the average_profile_rank, the average_reductions and the average_transition_risk_score. For this I will create some reprexes @kalashsinghal so that you know exactly on how to solve it. However, to create the reprex I would need your input @Tilmon. My problem is that if I multipy profile_rank and reduction targets I get the transition risk score for an individual product. If I now do this for each product I can calculate on company level the average profile rank and the average reduction targets of the company. Now the problem is if I multiple the average I get a different average transition risk score than I would get if I average the product based transition risk scores. Would be great if we could discuss this so that I can create a reprex for @kalashsinghal.
--Anne https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issue-2129684586

> Please note that I think Kalash already created all functions for all parts of the dataset, e.g (average_)transition_risk_score. I think the only column which is not in the tiltIndicator package is CO2_average on the company data sheet.
--Anne https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/177#issuecomment-1979685035

QUESTION

- [x] ml01. @AnneSchoenauer, I'm struggling to parse your request from the scattered information that seems to relate to averages. Can you explain once again what you need? 

If this is a duplicate of https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/178 then let me know and I'll happily close this issue.

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore. 

There are four averages on company level. 

Two averages are already created for sure  by Kalash the profile_ranking_avg and the reduction_targets_avg. See changelog if the tiltIndicatorAfter

> New columns profile_ranking_avg and reduction_targets_avg in the output at company level of profile_emissions*() and profile_sector*(), respectively ([@kalashsinghal](https://github.com/kalashsinghal) [#164](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/164)).

The co2_average is not created so far - but I approved your reprex this morning. 

The transition_risk_score_average is supposed to be generated. Kalash and I had discussions about it. It can be that it is part of the new function transition_risk_score. Would be great if you have a look in the tiltIndicator package if there is such a function. If not I will have a look if I find the ticket - I am at the Bundesbank so without computer. But I can look at it tonight! 

Does this help?

**Comment by maurolepore** [comment]
In the [examples of `score_transition_risk()`](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/score_transition_risk.html#ref-examples) I see the column `transition_risk_score_avg` -- so good news I don't need to calculate it myself :-)

However, in the googlesheet you shared I see columns that relate to transition risk but are not called exactly the same. Can you explain the relationship? I need to understand how I can use `transition_risk_score_avg` to meet the requirements you expressed via the googlesheet.

On the googlesheet you'll see a [related comment](https://docs.google.com/spreadsheets/d/1Gsz2N2-gqrttAooYuNgWrKfjLyA73Uj4w0xm_wN7fp4/edit?disco=AAABGjtr4A4).

![image](https://github.com/2DegreesInvesting/tiltIndicatorAfter/assets/5856545/96a3e809-9d78-448d-8cde-f5fe37111643)

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore - Thanks for noticing - good catch. 

I think the columns are just called wrongly. So it should be called: `transition_risk_score_avg`. We should then also call the benchmark as such right? So `benchmark_transition_risk_score_avg`. I just noticed that the reduction targets are called `average_reduction_targets`. Can we make sure that all averages are called in the same logic? So either

1. x_avg
2. x_average
3. avg_x
4. average_x

I would go with 1. or 3. depending on how you called the majority for now. 

Thanks @maurolepore!

**Comment by maurolepore** [comment]
Sounds good. It looks like most columns use the format `x_avg`.

**Comment by kalashsinghal** [comment]
Dear @AnneSchoenauer,

Regarding to your comment [here](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/182#issuecomment-1986775045):

I have changed the column name from `benchmark_tr_score` to `benchmark_tr_score_avg` using this [PR](https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/199). Please note that we already had columns names as `reduction_targets_avg` and `transition_risk_score_avg` at the company level. The reprex shows that "sector_level_at_company_level" has column name `reduction_targets_avg` and "transition_risk_score_at_company_level" has column names `transition_risk_score_avg` and `benchmark_tr_score_avg`. 

``` r
library(readr)
library(dplyr)
devtools::load_all(".")
#> ℹ Loading tiltIndicatorAfter
set.seed(1)

options(readr.show_col_types = FALSE)
toy_emissions_profile_products_ecoinvent <- read_csv(toy_emissions_profile_products_ecoinvent())
toy_emissions_profile_any_companies <- read_csv(toy_emissions_profile_any_companies())
toy_sector_profile_any_scenarios <- read_csv(toy_sector_profile_any_scenarios())
toy_sector_profile_companies <- read_csv(toy_sector_profile_companies())
toy_europages_companies <- read_csv(toy_europages_companies())
toy_ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
toy_ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
toy_ecoinvent_inputs <- read_csv(toy_ecoinvent_inputs())
toy_isic_name <- read_csv(toy_isic_name())

emissions_profile <- profile_emissions(
  companies = toy_emissions_profile_any_companies,
  co2 = toy_emissions_profile_products_ecoinvent,
  europages_companies = toy_europages_companies,
  ecoinvent_activities = toy_ecoinvent_activities,
  ecoinvent_europages = toy_ecoinvent_europages,
  isic = toy_isic_name)

sector_profile <- profile_sector(
  companies = toy_sector_profile_companies,
  scenarios = toy_sector_profile_any_scenarios,
  europages_companies = toy_europages_companies,
  ecoinvent_activities = toy_ecoinvent_activities,
  ecoinvent_europages = toy_ecoinvent_europages,
  isic = toy_isic_name)

emissions_profile_at_product_level <- unnest_product(emissions_profile)
sector_profile_at_product_level <- unnest_product(sector_profile)
sector_profile_at_company_level <- unnest_company(sector_profile)
sector_profile_at_company_level
#> # A tibble: 1,152 × 13
#>    companies_id        company_name  country sector_profile_share sector_profile
#>    <chr>               <chr>         <chr>                  <dbl> <chr>         
#>  1 antimonarchy_canine antimonarchy… germany                    0 high          
#>  2 antimonarchy_canine antimonarchy… germany                    1 medium        
#>  3 antimonarchy_canine antimonarchy… germany                    0 low           
#>  4 antimonarchy_canine antimonarchy… germany                    0 <NA>          
#>  5 antimonarchy_canine antimonarchy… germany                    1 high          
#>  6 antimonarchy_canine antimonarchy… germany                    0 medium        
#>  7 antimonarchy_canine antimonarchy… germany                    0 low           
#>  8 antimonarchy_canine antimonarchy… germany                    0 <NA>          
#>  9 antimonarchy_canine antimonarchy… germany                    1 high          
#> 10 antimonarchy_canine antimonarchy… germany                    0 medium        
#> # ℹ 1,142 more rows
#> # ℹ 8 more variables: scenario <chr>, year <chr>,
#> #   matching_certainty_company_average <chr>, company_city <chr>,
#> #   postcode <chr>, address <chr>, main_activity <chr>,
#> #   reduction_targets_avg <dbl>

transition_risk_score <- score_transition_risk(emissions_profile_at_product_level, sector_profile_at_product_level)
transition_risk_score_at_company_level <- unnest_company(transition_risk_score)
transition_risk_score_at_company_level
#> # A tibble: 1,728 × 9
#>    companies_id                      company_name country benchmark_tr_score_avg
#>    <chr>                             <chr>        <chr>   <chr>                 
#>  1 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2030_all     
#>  2 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2050_all     
#>  3 asteria_megalotomusquinquespinos… asteria_meg… austria NZ 2050_2030_all      
#>  4 asteria_megalotomusquinquespinos… asteria_meg… austria NZ 2050_2050_all      
#>  5 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2030_isic_4d…
#>  6 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2050_isic_4d…
#>  7 asteria_megalotomusquinquespinos… asteria_meg… austria NZ 2050_2030_isic_4di…
#>  8 asteria_megalotomusquinquespinos… asteria_meg… austria NZ 2050_2050_isic_4di…
#>  9 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2030_tilt_se…
#> 10 asteria_megalotomusquinquespinos… asteria_meg… austria 1.5C RPS_2050_tilt_se…
#> # ℹ 1,718 more rows
#> # ℹ 5 more variables: transition_risk_score_avg <dbl>, company_city <chr>,
#> #   postcode <chr>, address <chr>, main_activity <chr>
```

<sup>Created on 2024-03-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

cc' @maurolepore 

I have added `transition_risk_score_avg` and `benchmark_tr_score_avg` in the Bundesbank company level output using this [script](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/153#issuecomment-2004469926). Hence, this task is done and am closing it, however if you guyz have any issue with current solution after review, then please feel free to create separate tickets for the same. Thanks!
