### ISSUE TITLE
Relocate columns in a single place

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#224]
Different profiles seem to relocate columns differently. It would be nice to write a single function (wrapping `dplyr::rename()` that relocates columns consistently across profiles. Note `relocate()` works with patterns (via `matches()` and takes arguments `.before` and `.after`. 

This new function could be called after `profile_*impl()`, close to returning.

**Comment by kalashsinghal** [comment]
Already completed
