### ISSUE TITLE
Implement "best case" and "worst case" for `score_transition_risk()` on product-level

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicatorAfter#248]
Dear @kalashsinghal , 

please apply the best case / worst case logic from [#242](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/242) to the `score_transition_risk()` results (categories low, medium, high).

**Comment by AnneSchoenauer** [comment]
This can only be done if the ticket on the t[ransition risk categories](https://github.com/2DegreesInvesting/tiltIndicator/issues/788) is done. After this the same logic should be applied as for the emission profile.
