### ISSUE TITLE
Create a `coefficient_of_variation` variable

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicatorAfter#258]
Dear @Tilmon, 

What do you think about this approach for a sensitivity analysis? 

We calculate the coefficient_of_variation. The definition is: The coefficient of variation (CV) is the ratio of the standard deviation to the mean. The higher the coefficient of variation, the greater the level of dispersion around the mean. It is generally expressed as a percentage. 

I thought that this might be nice as we can compare the three cases with each other. We would calculate the mean and then see how much these deviate from each other. 

Here you can see how this would look like with real data: https://docs.google.com/spreadsheets/d/10DS1e-pwgat9n_tDG1cas4PbFwiPQjDHZQqskfpf5oQ/edit#gid=3027300 In sheet "company_level_sensitivity_analysis". 

What do you think? If you like it I would write a ticket on how to best integrate this for Kalash.

**Comment by Tilmon** [comment]
Hi @AnneSchoenauer I think that's a great idea! This gives a much better indication on the dispersion of the different weighting modes than only the standard deviation.

**Comment by AnneSchoenauer** [comment]
Perfect!

Dear @kalashsinghal. 

What we would need to implement such a coefficient of variation is the following: 

- standard deviation for each three transition_risk_scores (equal_weight, best_case, worst_case) for each transition_risk_score benchmark
- calculate the mean of the three transition_risk_scores
- And then calculate the coefficient_of_variation which is the standard_deviation/mean*100%. 

You can see these calculation [here](https://docs.google.com/spreadsheets/d/10DS1e-pwgat9n_tDG1cas4PbFwiPQjDHZQqskfpf5oQ/edit#gid=3027300) at the sheet 'company_level_sensitivity_analysis'. 

Let me know if something is unclear!

**Comment by AnneSchoenauer** [comment]
Dear @Tilmon maybe this is also something that we can do AFTER the data is generated? So that we do it similiar to the outlier analysis after the ouptut is done. This might give us the chance to start earlier with the generation?

**Comment by Tilmon** [comment]
@AnneSchoenauer agreed (as discussed today)!

**Comment by kalashsinghal** [comment]
> we would need to implement such a coefficient of variation

@AnneSchoenauer @Tilmon Should this be a new and permanent column at company level for transition risk indicator? Or Should it be part of new [tiltDataAnalysis](https://github.com/2DegreesInvesting/tiltDataAnalysis) repo?

If its part of transition risk indicator, then will it be part of webtool output?

**Comment by AnneSchoenauer** [comment]
Hi Kalash - a permanent column would actually be nice! We will update the XLS sheet so that it is included in the webtool.

**Comment by AnneSchoenauer** [comment]
And it would be nice to have it also for the relative emission indicator and the sector decarbonisation indicator.
