### ISSUE TITLE
Preserve NAs from unmatched products in transition_risk_score on company-level (`transition_risk_category_NA`)

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicatorAfter#283]
Hi @kalashsinghal , 

when reviewing the Bundesbank Output, I realized that the company-level results are still not preserving the NAs from unmatched products. See my Slack message for reference: 

> Hi [@Kalash](https://2investinginitiative.slack.com/team/U04NEP7U7T8)
> , thanks a lot! I reviewed it, but unfortunately, the issue with the preserved NAs for the transition risk score on company level is not resolved. The issue I described earlier today still exists, which is:
> On product-level, unmachted products are shown. E.g. `companies_id `== "123repair-deutschland_00000005109249-001" has 6 unmatched products which have NA for all result columns. That's correct!
> On company-level, however, this is not reflected anymore. If I chose for the `companies_id` == "123repair-deutschland_00000005109249-001" and `benchmark` == "all", then I still have in all rows `transition_risk_category_NA` == 0. But actually, the share of NAs should be in that case 6/9, because out of 9 ep_products , only 3 have a result, 6 are unmatched.

In the `emission_profile`() code and `sector_profile`() code, unmatched products are preserved correctly on company-level. Maybe you can check out if you can use a function from there? And if useful ask @maurolepore for help, as he's been working on preserving the NAs a lot already :) 

Thanks!

**Comment by maurolepore** [comment]
In case it helps , when exploring the reasons why we loose `NA` in `sector_profile()` I found the offender was `exclude_rows()` (https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/282#discussion_r1662996714).

**Comment by Tilmon** [comment]
Closing this because replaced by 2DegreesInvesting/tiltIndicatorAfter/issues/289
