### ISSUE TITLE
Add column `transition_risk_NA_share` on company-level

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicatorAfter#289]
Dear @kalashsinghal , 

this column is a slight modification of the column you added here 2DegreesInvesting/tiltIndicatorAfter/issues/286. 
The column `transition_risk_NA_share` should replace the other column and vary from the old one by reflecting different NA shares per benchmark. I'll come up with a draft later today and ask you to review & implement it. 

Thanks.

**Comment by Tilmon** [comment]
Hi @kalashsinghal , here is a peace of code for the desired column. Can you please review if that works in your view and if yes, add it to the output script? Thanks! It's not a reprex, but only dataset required is the product-level output for Budnesbank you shared. 

```{r}
library(dplyr)

# We need a column which shows unique count of ep_product. That one already exists (amount_of_distinct_products)

#1) We need a column (tr_NA_amount_all) which shows unique count of ep_product per benchmark_tr_score without tr result, i.e. where there is either no matched activity name (and hence never an emission_profile) or no reduction target (and hence never a sector_profile)
tr_prod_NA_sample <- tr_prod |> 
  group_by(companies_id) |> 
  mutate(tr_NA_amount_all = n_distinct(ep_product[is.na(matched_activity_name) | is.na(reduction_targets)]))

# 2) We need a column (tr_NA_amount_benchmarks) that shows per companies_id x benchmark_tr_score combination the amount of ep_product where transition_risk_score == NA
tr_prod_NA_sample <- tr_prod_NA_sample |> 
  group_by(companies_id, benchmark_tr_score) |> 
  mutate(tr_NA_amount_benchmarks = n_distinct(ep_product[is.na(transition_risk_score)]))

# 3) Now we add the new columns from 1) and 2) to show the total number of NAs, which is varying between benchmarks. Note that for those rows where either matched_activity_name == NA or reduction_targets == NA, we just use the tr_NA_amount_all. If we would add up the values from 1) and 2), we'd get a higher number than amount_of_distinct_products, which doesn't make sense. 
tr_prod_NA_sample <- tr_prod_NA_sample |> 
  group_by(companies_id, benchmark_tr_score) |> 
  mutate(tr_NA_total = if_else(is.na(matched_activity_name) | is.na(reduction_targets), tr_NA_amount_all, tr_NA_amount_all + tr_NA_amount_benchmarks))

# 4) We now add the actual column for the output (transition_risk_NA_share), which is defined as the ratio between tr_NA_total and amount_of_distinct_products per companies_id x benchmark_tr_score combination. 
tr_prod_NA_sample <- tr_prod_NA_sample |> 
  group_by(companies_id, benchmark_tr_score) |> 
  mutate(transition_risk_NA_share = tr_NA_total / amount_of_distinct_products)

# 5) Cleaning. We remove irrelevant columns. 
tr_prod_NA_sample <- tr_prod_NA_sample |> 
  select(-c("tr_NA_amount_all", "tr_NA_amount_benchmarks", "tr_NA_total"))

#6) Checks. Any NAs in the new columns or values below 0 or above 1? 
na_rows <- tr_prod_NA_sample |> 
  filter(is.na(transition_risk_NA_share))

rows_between_1_and_0 <- tr_prod_NA_sample |> 
  filter(transition_risk_NA_share < 0 | transition_risk_NA_share > 1)

```

**Comment by kalashsinghal** [comment]
@Tilmon This code seems to be on product level, but the title says its on product level. Please check again! Thanks!

**Comment by Tilmon** [comment]
@kalashsinghal yea, that's true... Is it not possible to show that same column on company-level as well?

**Comment by kalashsinghal** [comment]
@Tilmon We don't have `matched_activity_name` column on company level. So, I can't calculate it on company level without adding `matched_activity_name` on company level. Do you want me to do `matched_activity_name` on company level? Or can I just join the required column from product level to company level output?

**Comment by kalashsinghal** [comment]
> #1) We need a column (tr_NA_amount_all) which shows unique count of ep_product per benchmark_tr_score without tr result, i.e. where there is either no matched activity name (and hence never an emission_profile) or no reduction target (and hence never a sector_profile)
tr_prod_NA_sample <- tr_prod |> 
  group_by(companies_id)

@Tilmon Here you said that the `unique count of ep_product per benchmark_tr_score ` but you didn't used the `benchmark_tr_score` in the code. Please clarify which one is right!

**Comment by Tilmon** [comment]
@kalashsinghal well spotted! The description is wrong. Should just say that I count the number of unique ep_product that never have a result - not per benchmark_tr_score.
The grouping by benchmark_tr_score only becomes relevant in the next steps.
I'll adjust description later, now only on my phone. But thanks for double checking!!
