### ISSUE TITLE
Create dedicated documentation page for "Input Analysis"

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicatorAfter#309]
Hi @kalashsinghal , 

for reporting, we need a proof for the input indicator work we've done so far. Therefore, @AnneSchoenauer and I were thinking that it would be useful to have a dedicated page where it's documented which input anayses tilt offers. This could e.g. be a separate page in the tiltIndicatorAfter Article or another way if you have other ideas. 

How this page should look like (high level): 

1. title "tilt Input Analysis"
2. Introductory text (@Tilmon will provide)
3. 1. Component: Emission Upstream Indicator: Link to documentation, snippet of code, sample results
4. 2. Component: Sector Upstream Indicator: Link to documentation, snippet of code, sample results
5. 3. Component: Supplier Heatmap: Short description + code from bob + screenshot of map
6. **OPTIONAL**: If time allows, create barcharts for input indicator results --> @kalashsinghal let's touch base before you start working on it and see if it's worth it.

**Comment by kalashsinghal** [comment]
Hi @Tilmon,

Just to get the basic understanding of where we stand with the input indicators, please have a look at the output columns from the function `profile_emissions_upstream` in this [example article](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html#ref-examples). Similarly, for the output columns of the function `profile_sector_upstream`, please have a look at this [example article](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_sector_upstream.html#ref-examples). 

I am happy to create a separate article for the input indicators, however it would be great to have more understanding on how this new article could provide more detailed outlook as expected by you. Therefore, let's discuss the expectations on this article in the tech sprint :)

**Comment by Tilmon** [comment]
Hi @kalashsinghal , 

this is the code that Bob used to create the heatmaps for the inputs: https://github.com/2DegreesInvesting/NLPTiltMatch/blob/main/eurocaps/analysis.ipynb

The code is in Python, but that is OK for the reporting. Also, the code contains real company names. Could you replace the real company names with sample company names? Also, we only need the code for this heatmap: 
![Image](https://github.com/user-attachments/assets/06176dc1-2059-48df-8dc0-a4f38219cc29)

**Comment by Tilmon** [comment]
Hi @kalashsinghal , 

here is the text for the page: https://docs.google.com/document/d/1vrEcsNDzEZMvTsF9zAIrZ9mufz93UZgo8jWW9_xbOBk/edit

Please read through it carefully for a double check and let me know if you think that's clear. Feel also free to suggest changes in suggestion mode.

**Comment by kalashsinghal** [comment]
Hi @Tilmon ,

The heatmap you mentioned in this [comment](https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/309#issuecomment-2352270187) is made from the transition risk score column. The input indicators do not calculate the transition risk score as the transition risk methodology is only applied to the emission and sector indicators. Do you agree? If yes, then please update the heatmap I need to create on the article?

**Comment by Tilmon** [comment]
Hi @kalashsinghal, 

ah damn. I don't know why that is so.... I'll double check with Bob and then get back to you...

**Comment by kalashsinghal** [comment]
Closing via [article](https://2degreesinvesting.github.io/tiltIndicatorAfter/articles/tilt_input_analysis.html) after review.

cc' @Tilmon
