### ISSUE TITLE
Clarify where datasets come from, and if we can "pre-compute" on them

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#36]
@kalashsinghal

I'm familiar with datasets that come from tiltIndicator, but I'm not familiar with these other datasets:

* `ecoinvent_activities`
* `ecoinvent_inputs`
* `ep_companies`
* `isic_tilt_mapper`
* `matches_mapper`

Can you please clarify where each comes from and who provides it? My intention is to see if some of those datasets vary less frequently than others.

I'm most interested in understanding if we could pre-compute this:

```r
prepare_matches_mapper(matches_mapper, ecoinvent_activities)
```

This seems to be slow and appears in many places. If we could do this once and reuse it, then we could potentially save a lot of computations.

And if this varies slowly enough AND we control it, then maybe we could move it to data-management? If so our applications wouldn't need to compute it at run-time.

It's fine if you don't know. AFAIK this originally comes from Tilman's code, so it's likely we'll need to ask Anne.

**Comment by kalashsinghal** [comment]
Dear @maurolepore 

These datasets come from the final output of tiltIndicatorBefore package. Here are the outputs from the package: https://drive.google.com/drive/folders/1AbSGCGFVcRM3zLfPg5FdwScTRRaCbIws. Each of the respective datasets come from these csv files:

ecoinvent_activities - ei_activities_overview.csv
ecoinvent_inputs - ei_input_data.csv
ep_companies - ep_companies.csv
isic_tilt_mapper - tilt_isic_mapper_2023-07-20.csv
matches_mapper - mapper_ep_ei.csv

I have created sample files from these datasets to create snapshots in tiltIndicatorAfter. I have used this [Rstudio server](http://64.226.79.196:8788/auth-sign-in?appUri=%2F) to create sample datasets created by Tilman. The login credentials to this Rstudio server are:
username: rstudio
Password: AzUSdgCv_QU2

Please use `projects/tiltIndicatorAfter/sample_input_data.Rmd` file to see how I created these sample datasets for tiltIndicatorAfter package.

**Comment by maurolepore** [comment]
From Kalash:

--

Dear @maurolepore 

These datasets come from the final output of tiltIndicatorBefore package. Here are the outputs from the package: https://drive.google.com/drive/folders/1AbSGCGFVcRM3zLfPg5FdwScTRRaCbIws. Each of the respective datasets come from these csv files:

ecoinvent_activities - ei_activities_overview.csv
ecoinvent_inputs - ei_input_data.csv
ep_companies - ep_companies.csv
isic_tilt_mapper - tilt_isic_mapper_2023-07-20.csv
matches_mapper - mapper_ep_ei.csv

I have created sample files from these datasets to create snapshots in tiltIndicatorAfter. I have used this [Rstudio server](http://64.226.79.196:8788/auth-sign-in?appUri=%2F) to create sample datasets created by Tilman. 

...

Please use `projects/tiltIndicatorAfter/sample_input_data.Rmd` file to see how I created these sample datasets for tiltIndicatorAfter package.

**Comment by maurolepore** [comment]
Thanks @kalashsinghal,

Does that mean that the data-management team could do this in advance and give the tilt system the result? 

```r
prepare_matches_mapper(matches_mapper, ecoinvent_activities)
```

That would make the tilt system much faster. That computation is in every function of tiltIndicatorAfter, and it's a pretty slow one. 

In other words, does the data-management team have complete power over those datasets? Or would those datasets be inputs that the user must provide?

**Comment by kalashsinghal** [comment]
@maurolepore Yes, the data-management team have complete power over these datasets. I can make the function `prepare_matches_mapper` and output file from this function as part of tiltIndicatorBefore code. Please let me know if it's a good idea!

**Comment by maurolepore** [comment]
Yeah, that would be great! 
When you create that issue in tiltIndocatorBefore, can you please share its link here? 

BTW, are those two datasets toy data or real data? (I would think it's toy data, but the size is large so maybe it's real data?)

**Comment by maurolepore** [comment]
This is now clear so I'll close and follow up in https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/63

**Comment by kalashsinghal** [comment]
@maurolepore Here is the issue to add `prepare_matches_mapper` to tiltIndicatorBefore code: https://github.com/2DegreesInvesting/NLPTiltMatch/issues/65

Yes these two datasets are real datasets and hence the `prepare_matches_mapper` function is slow.

**Comment by maurolepore** [comment]
Awsome, thanks for explaining. 
Just to double check, those datasets are public, right? (I'm pretty sure you said yes but better safe than sorry).

**Comment by kalashsinghal** [comment]
My bad, Yes those datasets are public
