### ISSUE TITLE
Develop toy data to test non-missing outputs of `matched_*` and `unit`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicatorAfter#68]
Relates to https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/66

Develop a dataset that allows us to test missing and non-missing outputs of the columns `matchec_*` and `unit`.

Maybe we can start backwards from real data, and identifying 1 or a few rows in the input that lead to a match. Then replacing the real row with a fake row -- maybe by hand, or with chatGTP, or R packages dedicated to creating fake data.

**Comment by kalashsinghal** [comment]
@maurolepore I created toy data in #69. Please let me know if additional work is needed on this issue. If not, then I will close it.

**Comment by maurolepore** [comment]
Thanks @kalashsinghal 

Closed by https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/69
