### ISSUE TITLE
Sector profile product has for some companies `NA` in the `tilt_sector

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicatorAfter#72]
Ìf you look [here](https://docs.google.com/spreadsheets/d/1pm3y2eYHVhDDevwebyld_zcfk0MUEdHMojcXx3-cU8s/edit#gid=206376910) the company `040 tegelzetter` has `NA` when it comes to the `tilt_sector`column. Can we investigate why this is the case please? And how many times this is the case?

**Comment by kalashsinghal** [comment]
Similar test for pctr needs to be written
